---
- hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: puppet-repo }

- hosts: master
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: puppet-master }

- hosts: agent
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: puppet-agent }

- hosts: master
  become: true
  become_user: root
  vars_files:
    - vars/all.yml
  tasks: []
  roles:
    - { role: sign-agent }
