---
- name: Install puppet master package
  yum:
    name: '{{ item.name }}'
    state: present
  with_items:
    - { name: puppetserver }

- name: Change puppet master hostname
  hostname:
    name: '{{ master_hostname }}'

- name: Start & enable puppetserver service
  service:
    name: puppetserver
    state: started
    enabled: yes

- name: Copy site.pp test file
  copy:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  with_items:
    - { source: "site.pp", destination: "/etc/puppetlabs/code/environments/production/manifests/" }
